### ISSUE TITLE
[프로젝트버그] 

### ISSUE THREAD

**Issue by 0r0loo** [hwasurr/graphql-book-fullstack-project#10]
### 🐛 버그가 발견된 페이지

112

### 🐞 버그를 설명해주세요.

react array에서 key 에러납니다
```
new Array(6).fill(0).map((x) => <Skeleton key={x} height="400px" />
```
=>
```
new Array(6).fill(0).map((_, index) => <Skeleton key={index} height="400px" />
```

### 🍉 버그를 재현할 방법을 알려주세요

node v18
vite

### 🌏 오류가 발생한 환경의 OS는 무엇인가요?

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by hwasurr** [comment]
안녕하세요, @0r0loo 님! 버그 제보 감사드립니다.

작성해주신대로, 아래의 코드블럭 대로 작성하여야 합니다.
해당 버그 사항을 알려진 버그 목록에 추가하도록 하겠습니다.

감사합니다.

**Comment by hwasurr** [comment]
[버그 목록 문서](https://github.com/hwasurr/graphql-book-fullstack-project/blob/master/bug-list.md#3-p-112-%EB%91%90-%EB%B2%88%EC%A7%B8-%EC%BD%94%EB%93%9C%EB%B8%94%EB%9F%AD-%EC%97%AC%EB%9F%AC-%EA%B0%9C%EC%9D%98-skeleton-%EC%BB%B4%ED%8F%AC%EB%84%8C%ED%8A%B8%EB%A5%BC-%EB%A0%8C%EB%8D%94%EB%A7%81-%ED%95%A0-%EB%95%8C-%EB%8F%99%EC%9D%BC%ED%95%9C-%EA%B0%92%EC%9C%BC%EB%A1%9C-key%EB%A5%BC-%EC%84%A4%EC%A0%95%ED%95%98%EB%8A%94-%EB%AC%B8%EC%A0%9C)에 해당 버그 내용을 추가하였습니다.

감사합니다. 이슈는 닫도록 하겠습니다!
