### ISSUE TITLE
[프로젝트버그] 에러 확인 요청드립니다. 

### ISSUE THREAD

**Issue by choyccc** [hwasurr/graphql-book-fullstack-project#11]
### 🐛 버그가 발견된 페이지

98페이지까지 작성하고 yarn dev 실행 후

### 🐞 버그를 설명해주세요.

yarn dev 실행 후 다음과 같은 에러가 발생합니다. 
<img width="986" alt="p98" src="https://user-images.githubusercontent.com/3749555/227425800-537af4b4-0746-4aec-aad1-3e26a01d609b.png">

### 🍉 버그를 재현할 방법을 알려주세요

98페이지
index.ts까지 작성 후..

모듈 모두 삭제 후 압축 파일 공유 드립니다. 

확인 요청 드립니다. 미리 감사드립니다. 
[graphql-book-fullstack-project.zip](https://github.com/hwasurr/graphql-book-fullstack-project/files/11058487/graphql-book-fullstack-project.zip)

### 🌏 오류가 발생한 환경의 OS는 무엇인가요?

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by hwasurr** [comment]
안녕하세요~ 답변이 늦어 죄송합니다! ㅠㅠ 

먼저 책을 읽어 주셔서 감사합니다.

첨부해주신 내용 중, server 폴더에 tsconfig 파일이 없어, 프로젝트에서 사용하고 있는 타입스크립트 버전에서는 아직 실험적인 기술인 Decorator를 사용할 수 없다는 오류가 보이고 있는 것 같습니다.

https://github.com/hwasurr/graphql-book-fullstack-project/blob/master/project/server/tsconfig.json 에서 server 프로젝트의 tsconfig 설정을 확인할 수 있습니다.

더불어 직접 프로젝트를 구축하는 것에는 버전 등 문제가 발생할 여지가 크므로, 현재 레파지토리를 fork & clone 하여 브랜치별로 구성된 프로젝트를 따라 진행하는 것을 추천드립니다!

프로젝트 구성이 완료된 브랜치는 chapter-3 입니다. 참고부탁드립니다!

**Comment by choyccc** [comment]
네 말씀하신 대로 해보겠습니다. 확인 감사합니다.
