### ISSUE TITLE
[오타/문장오류] [질문/기타]

### ISSUE THREAD

**Issue by fluorjo** [hwasurr/graphql-book-fullstack-project#14]
### 🐛 오타 또는 문장 오류가 발견된 페이지

113p~114p

### 🍔 오타 또는 문장 오류 내용

안녕하세요. 책 읽다가 오타가 발견되고 질문도 있어서 글 남깁니다.

https://github.com/hwasurr/graphql-book-fullstack-project/blob/master/project/web/src/components/film/FilmCard.tsx
FilmCard 부분의 코드 관련된 부분입니다. 

1. 114 페이지 코드 부분의 10번째 줄에
`<Image src={film.posterImg} 
`부분이
`<Image src={film.posterImg} />`
로 수정돼야 할 것 같습니다 끝에 />가 빠졌습니다. 

다만 깃허브에는 올바르게 돼있어서 참고해 해결할 수 있었습니다.

------ 

2. 113페이지 코드 부분 밑에서 6번째 줄에 
` film: FilmsQuery['films']['films'][0]`
라고 ['films']가 두 번 나와있는데요.

이 부분가 관련해 122페이지 진행 전, filmlist 컴포넌트 수정 전까지는 ['films']를 두 번 쓴 것에 대해 아래와 같은 에러가 나왔습니다. 

- '({ __typename?: "Film" | undefined; } & Pick<Film, "id" | "title" | "subtitle" | "runningTime" | "release" | "posterImg"> & { director: { __typename?: "Director" | undefined; } & Pick<...>; })[]' 형식에 'films' 속성이 없습니다.ts(2339)

그런데 122페이지까지 진행한 뒤에는 두 번 쓴 게 올바른 걸로 돼서 수정을 했습니다. 

['films']['films'] 가 어떤 역할을 하는지 궁금합니다. 
[paginatedfilms] 와 film 배열을 불러오기 위해 이렇게 작성해야 하는 것이었을까요?

----

3. p.133 코드 부분 밑에서 12번째 부분 
`href="/signup` 
부분이 에러가 납니다. 
button 에 href 속성이 없다고 나옵니다. 

밑에 ` as ={RouterLink} to="/signup" `  이 있어서 href 부분은 지워도 문제 없이 작동되는데, 혹시 버전이 달라지면서 사용법이 바뀐 걸까요?

----
책 잘 보면서 많이 배우고 있습니다. 좋은 책 집필해 주셔서 감사합니다.

**Comment by hwasurr** [comment]
> https://github.com/hwasurr/graphql-book-fullstack-project/blob/master/project/web/src/components/film/FilmCard.tsx
FilmCard 부분의 코드 관련된 부분입니다.
114 페이지 코드 부분의 10번째 줄에
`<Image src={film.posterImg}`  부분이
`<Image src={film.posterImg} />`
로 수정돼야 할 것 같습니다 끝에 />가 빠졌습니다.
다만 깃허브에는 올바르게 돼있어서 참고해 해결할 수 있었습니다.

오타 제보 정말 감사드립니다! 👍  [오타 목록](https://github.com/hwasurr/graphql-book-fullstack-project/blob/master/typo-list.md)에 해당 내용을 추가하였습니다!

**Comment by hwasurr** [comment]
> 113페이지 코드 부분 밑에서 6번째 줄에
 film: FilmsQuery['films']['films'][0]
라고 ['films']가 두 번 나와있는데요.
이 부분가 관련해 122페이지 진행 전, filmlist 컴포넌트 수정 전까지는 ['films']를 두 번 쓴 것에 대해 아래와 같은 에러가 나왔습니다.
> 
> '({ __typename?: "Film" | undefined; } & Pick<Film, "id" | "title" | "subtitle" | "runningTime" | "release" | "posterImg"> & { director: { __typename?: "Director" | undefined; } & Pick<...>; })[]' 형식에 'films' 속성이 없습니다.ts(2339)
그런데 122페이지까지 진행한 뒤에는 두 번 쓴 게 올바른 걸로 돼서 수정을 했습니다.
> 
> ['films']['films'] 가 어떤 역할을 하는지 궁금합니다.
[paginatedfilms] 와 film 배열을 불러오기 위해 이렇게 작성해야 하는 것이었을까요?

작업한 결과물을 책으로 옮기는 방식으로 책을 작성해 책 내용 상, 순서가 올바르지 못한 부분인 것 같습니다. 부족한 내용을 전달해드려 죄송스럽네요. ㅠㅠ 말씀하신 대로, 페이지네이션 처리 전 까지는 `['films']` 한 번만 지정하는 것이 맞고, 페이지네이션 처리 이후 부터는 `['films']['films']` 와 같이 두 번 작성하는 것이 맞습니다.

현재 책에서의 `FilmsQuery`는 Apollo client용 GraphQL Codegen에 의해 생성된 `graphql/queries/films.graphql` 요청에 대응하는 타입 입니다. 

```graphql
# graphql/queries/films.graphql
query Films($limit: Int, $cursor: Int) {
    films(limit: $limit, cursor: $cursor) {
        cursor
        films {
            id
            title
            subtitle
            runningTime
            director {
                name
            }
            release
            posterImg
        }
    }
}
```

116p 부터 작업한 페이지네이션 작업이 완료된 이후 요청한 쿼리를 살펴보시면, `films` 쿼리는 `cursor`와, `films` 목록 필드를 가지는 오브젝트 타입이므로 총 두 번의 `films` 필드를 정의하게 됩니다.
다시 말해 첫 번째 `films`는 페이지 처리된 영화 목록 반환 오브젝트 타입 `PaginatedFilms` 을, 두 번째 `films`는 `PaginatedFilms` 의 `Film` 오브젝트 타입의 배열 `films` 필드를 의미합니다.

`FilmCard` 컴포넌트는 필름 목록 중 한 개의 필름에 대한 데이터를 바탕으로 구성한 컴포넌트로, props로 받아오는 데이터는 필름 목록 중 한 개의 필름에 대한 데이터입니다.
이에 대한 컴포넌트 프로퍼티 타입을 지정하기 위해 `FilmsQuery` 타입에서 `films` 필드를 선택하고, 그 하위의 `films` 필드를 가져온 이후, [배열 요소의 타입을 지정하기 위해 `[0]` 과 같이 인덱싱](https://www.typescriptlang.org/docs/handbook/2/indexed-access-types.html)하여 개별 `Film` 타입을 명시한 것입니다.

도움이 되셨으면 좋겠습니다.

**Comment by hwasurr** [comment]
> p.133 코드 부분 밑에서 12번째 부분
href="/signup
부분이 에러가 납니다.
button 에 href 속성이 없다고 나옵니다.
밑에 as ={RouterLink} to="/signup" 이 있어서 href 부분은 지워도 문제 없이 작동되는데, 혹시 버전이 달라지면서 사용법이 바뀐 걸까요?

자세히 확인해보지는 않았지만, 아마 react-router-dom 의 `Link` 의 타입 및 API 변화에 따른 이슈인 것 같습니다. 현재 깃헙 리파지토리의 내용을 그대로 클론하였을 때는 발생하지 않는 것 같습니다!

현재 리파지토리의 react-router-dom 버전에서는 `Link`컴포넌트의 프로퍼티 타입 `LinkProps`가 다음과 같이 html `a` 태그의 애트리뷰트 타입을 상속받는 것으로 되으므로 `href` 프로퍼티 지정이 가능합니다.

```ts
export interface LinkProps<S = H.LocationState> extends React.AnchorHTMLAttributes<HTMLAnchorElement> {
    component?: React.ComponentType<any> | undefined;
    to: H.LocationDescriptor<S> | ((location: H.Location<S>) => H.LocationDescriptor<S>);
    replace?: boolean | undefined;
    innerRef?: React.Ref<HTMLAnchorElement> | undefined;
```

**Comment by hwasurr** [comment]
제보 및 문의 감사드립니다

또한 부족한 책 읽어주셔서 정말로 감사드립니다!!!

이슈는 해결상태로 두겠습니다!
새로운 문의/제보거리가 있다면 새로운 이슈로,
현재 이슈와 관련한 또다른 문의사항이나 제보사항이 발생한다면 현재 이슈를 재오픈하여 작성해주시면 감사드리겠습니다

**Comment by fluorjo** [comment]
답변 감사합니다!

**Comment by fluorjo** [comment]
> 제보 및 문의 감사드립니다
> 
> 또한 부족한 책 읽어주셔서 정말로 감사드립니다!!!
> 
> 이슈는 해결상태로 두겠습니다! 새로운 문의/제보거리가 있다면 새로운 이슈로, 현재 이슈와 관련한 또다른 문의사항이나 제보사항이 발생한다면 현재 이슈를 재오픈하여 작성해주시면 감사드리겠습니다


답변 감사합니다!
