### ISSUE TITLE
[오타/문장오류] react-hook-form의 register 옵션 min

### ISSUE THREAD

**Issue by NarciSource** [hwasurr/graphql-book-fullstack-project#17]
### 🐛 오타 또는 문장 오류가 발견된 페이지

181p

### 🍔 오타 또는 문장 오류 내용

react-hook-form의 register 옵션에 min을 minLength로 바꿔야하겠습니다. [SignUpForm.tsx](https://github.com/hwasurr/graphql-book-fullstack-project/blob/master/project/web/src/components/auth/SignUpForm.tsx#L97C13-L97C16)

암호 필드 자리수를 강제하려는 것인데,
min은 숫자 값의 범위를 검사하고
minLength가 문자열의 길이를 검사하네요. [docs](https://react-hook-form.com/docs/useform/register)

다음 pattern 옵션에 정규식으로 8자리 이상 조건이 또 있어서 체크가 잘 안되었나봐요.

**Comment by hwasurr** [comment]
안녕하세요. 제보 주신 내용 확인하였으며 [f374c8e](https://github.com/hwasurr/graphql-book-fullstack-project/commit/f374c8e50187e4df1c7376f0ce350b5d08f5ffc8) 에서 수정하였습니다. [오타목록](https://github.com/hwasurr/graphql-book-fullstack-project/blob/master/typo-list.md)에서도 확인가능하도록 조치하였습니다.

제보 정말 감사드립니다!!
