### ISSUE TITLE
[질문/기타] 안녕하세요? ESlint 설정 중 진행되지 않는 부분이 있어 질문드립니다.

### ISSUE THREAD

**Issue by Gomdorydory** [hwasurr/graphql-book-fullstack-project#2]
### 🍥 질문사항 또는 도움요청 사항

안녕하세요? 
85-90쪽까지 진행된 코딩 스타일 및 규칙 적용에서 오류가 나서 글 남깁니다.
도서에 제시해주신대로, 모든 설정을 완료했는데,

.eslintrc.js 파일부터 모든 파일에
{ } [ ] , 와 같은 기호에는 모두 에러 표시가 뜹니다.

설정 전에는 빨간 줄이 뜨지 않아서, 설정 후에 무언가 잘못 된 것 같은데 구글링을 해보아도 비슷한 경우가 없는 것 같아 여쭙습니다.

오타가 있을까 싶어, 남겨주신 프로젝트를 복붙하여 설정했음에도 불구하고 같은 오류가 뜹니다.

어떻게 하면 좋을까요?

**Comment by hwasurr** [comment]
안녕하세요! 문의에 감사드립니다.

에러 내용이 어떻게 되는 지 확인하실 수 있으신가요?

혹시 에러가 표시되는 에디터화면이나 에러 내용을 캡쳐해 주실 수 있다면 올바른 도움 드릴 수 있을 것 같습니다.

**Comment by Gomdorydory** [comment]
![에러](https://user-images.githubusercontent.com/95998018/198993777-e32d95b0-9c85-4e7f-b97a-c66c728356d8.JPG)
![에러2](https://user-images.githubusercontent.com/95998018/198994006-4712471a-f5e2-4339-8228-e06a51767af1.JPG)

파일을 클릭해서 들어가면 다음과 같이 빨간줄이 뜹니다.
파일 밖으로 나가면 다시 빨간줄이 사라집니다.

편집기로 열어본 파일은 모두 빨간줄이 생깁니다.
(에러 메세지가 따로 뜨는 것이 아니라, 빨간줄이 뜨는 것 입니다.)

**Comment by hwasurr** [comment]
캡쳐 첨부 감사드립니다!

`endofline` 설정으로 인한 문제로 보입니다.  책 내용 그대로 따라하셨다면, ESLint의 기본 `linebreak-style` 옵션은 `"off"`로 지정되어 있고, `eslint-plugin-prettier`, `eslint-config-prettier` 에 의해 Prettier 설정을 따르도록 구성되어 있을 것입니다. 

현재 작업하시는 프로젝트의 `.prettierrc` 파일에서, `endOfLine` 옵션 설정도 책에서의 내용과 동일하게 `"auto"`로 지정되어 있는지 확인하신 뒤 동일하게 지정되어 있는 지 확인 가능할까요?

**Comment by hwasurr** [comment]
`.prettierrc` 파일의 endOfLine 옵션을 설정했는데도 불구하고 동일한 현상이 반복된다면, 다음 두 블로그 글을 확인하신 뒤 처리해주세요.

처리 이후에도 동일한 현상이 반복된다면 다시 말씀해주세요!

- https://simsimjae.medium.com/vscode%EB%A5%BC-%EC%82%AC%EC%9A%A9%ED%95%A0%EB%95%8C-%EC%9C%88%EB%8F%84%EC%9A%B0%EC%9D%98-crlf%EC%99%80-%EB%A7%A5%EC%9D%98-lf-%EB%AC%B8%EC%A0%9C-%ED%95%B4%EA%B2%B0-51ba3fb76cc3

- https://firsteast.tistory.com/148

**Comment by Gomdorydory** [comment]
감사합니다! 덕분에 잘 해결되었습니다!

책에서는 endOfLine 부분이 없는 것 같습니다. 확인해보시면 좋을 것 같습니다! (87쪽)
책 내용은 캡처하면 안될 것같아 텍스트로만 남깁니다.

{
  "printWidth": 120,
  "tabWidth": 2,
  "singleQuote": true,
  "trailingComma": "all",
  "bracketSpacing": true,
  "semi": true,
  "useTabs": false,
}

감사합니다!

**Comment by hwasurr** [comment]
앗 ㅜㅜ 책에 빠진 부분이 있었네요..
해결되어서 다행입니다!

감사합니다. 이슈는 완료처리하도록 하겠습니다.
