### ISSUE TITLE
[질문/기타] type-graphql의 graphql 16 대응 관련 문의드립니다. 

### ISSUE THREAD

**Issue by bulhwi** [hwasurr/graphql-book-fullstack-project#4]
### 🍥 질문사항 또는 도움요청 사항

안녕하세요. 

저서 94페이지에서 
type-graphql에 인스톨이 정상적으로 되지 않습니다. 

찾아보면 graphql 15만 지원을 하는거 같은데 맞나요 ???
graphql의 버전을 15로 맞춰서 진행을 하면되겠지만, 
16버전에 경우에는 어떻게 진행을 하는게 좋을지 질문드립니다.

![image](https://user-images.githubusercontent.com/24216638/208298271-86311996-875c-4f6c-91a1-62d7f652c275.png)
관련 에러 공유드립니당 

감사합니다.

**Comment by hwasurr** [comment]
안녕하세요! 먼저, 문의에 감사드립니다.

넵. 말씀하신대로 `type-graphql`의 현재 최신 배포 버전 1.1.1 에서는 `graphql` 16 버전을 지원하지 않는 것으로 보입니다.

책의 예제를 따라가며 직접 환경을 구성한다면, 책의 패키지 설치와 관련한 내용에서 버전을 명시해두지 않았으므로 @bulhwi 님께서 겪으신 문제를 다른 여러 독자분들이 겪을 수 있다는 생각이 듭니다.ㅠㅠ

책의 예제를 올바르게 실행하기 위해서는 현재 깃헙 리파지토리의 master 브랜치의 `project/server`와 `project/web`의 `package.json` 파일을 참고하여 버전을 그대로 따라가는 것이 안전하다고 말씀드립니다.

추가로, `graphql` 16 버전으로 작업하고 싶으시다면 다음 명령어를 통해 `graphql` 16버전과 호환되는 `type-graphql`의 베타버전을 설치하여 작업을 진행할 수 있습니다. 그러나 버전 업그레이드로 인해 생겨날 수 있는 새로운 다른 미지의 문제들은 따로 해결해 나가야할 것으로 보입니다. 버전을 변경한 이후에 발생하는 문제와 관련해서는 type-graphql 리파지토리의 이슈를 확인하거나 제안할 수 있습니다.

```bash
# project/server 아래에서
yarn add type-graphql@next
```
또는
```bash
# project/server 아래에서
yarn add type-graphql@2.0.0-beta.1
```

**Comment by bulhwi** [comment]
@hwasurr 
넵, 답변 너무너무 감사드립니당 ㅎㅎㅎ
권해주신대로 책에서의 예제 버전에 맞춰 진행 하면서 정독하고 있습니다.

감사합니당~!

**Comment by hwasurr** [comment]
이슈를 마감하도록 하겠습니다! 다시 한번 읽어주셔서 감사합니다!

**Comment by hwasurr** [comment]
[버그 목록 문서](https://github.com/hwasurr/graphql-book-fullstack-project/blob/master/bug-list.md#2-type-graphql%EC%9D%98-graphql-16-%EB%B2%84%EC%A0%84-%EC%A7%80%EC%9B%90-%EA%B4%80%EB%A0%A8-%EB%AC%B8%EC%A0%9C) 에 해당 버그 내용을 작성하였습니다.
