### ISSUE TITLE
[질문/기타] Chapter-5 리프레시토큰 관련 질문 (p.233)

### ISSUE THREAD

**Issue by skylogin** [hwasurr/graphql-book-fullstack-project#5]
### 🍥 질문사항 또는 도움요청 사항

안녕하세요? 챕터5의 자동 새로고침 요청쪽 질문드립니다.

accessToken의 만료를 10초로 설정하고 refreshToken을 받아 자동으로 만료된 accessToken을 갱신하는 부분을 학습중인데요.
설명해주신 부분대로 진행을 해보아도 access token expired 메시지가 나오며 로그인된 상태가 유지되지 않네요.

쿠키에 refreshtoken값이 있는 것과 redis에 조회했을때 동일한 값임을 확인했고, 심지어 Users 리졸버를 통해 refreshAccessToken 함수가 실행되어 새 토큰값이 발행되는 것 까지 확인했습니다. (다만 그 이후 로직 --제 생각엔 accessToken을 갱신하고 로그인이 유지되도록 처리 -- 이 진행되지 않네요..)

혹시 제가 놓친 부분이 있을까싶어, chapter-5 브랜치와 master 브랜치를 체크아웃해서 토큰만료일 소스만 수정해보아도 동일하게 로그인유지가 되지않습니다.

어느 부분을 수정해야 할까요?

http://localhost:4000/graphql 에서 refreshAccessToken 뮤테이션을 실행하면 null로 응답됩니다. (그 전에 책의 진행상황처럼 로그인 뮤테이션을 수행해도 말이죠)

**Comment by skylogin** [comment]
이런...자문자답하고 이슈닫겠습니다.

graphql API에서도 null이 나오길래 서버쪽 refreshToken 가져오는 로직에서 문제가 있다고 생각했는데, 그건 그냥 graphql API studio의 버그인지.. 쿠키를 allow 해놓아도 저장되지 않아서 발생한 거였네요.

클라이언트부분에서 에러가 나서 localStorage에 제대로 setItem 하지 못한 건이였습니다.

**Comment by hwasurr** [comment]
@skylogin 님 질문 감사드립니다!

**Comment by fluorjo** [comment]
안녕하세요. 저도 여기서 막혔습니다만 혹시 어떻게 해결하셨는지 여쭤봐도 될까요?

토큰이 갱신이 안 되고project/web/src/apollo/auth.ts 의 _apollolcient 부분에서 " Uncaught TypeError: Cannot read properties of undefined (reading 'mutate')  이런 에러가 뜹니다.

**Comment by hwasurr** [comment]
토큰 리프레시와 관련한 부분의 책 내용에 apolloClient 를 전역변수로 지정하는 부분에서 누락이 있는 것으로 확인하였습니다, 

`createApolloClient` 함수를 다음과 같이 수정하면 `errorLink`에 `apolloClient` 가 undefined로 들어가서 발생하는 `Uncaught TypeError: Cannot read properties of undefined (reading 'mutate')` 의 문제가 해결됩니다.
(@fluorjo)

```ts

let apolloClient: ApolloClient<NormalizedCacheObject>;

... 링크들

export const createApolloClient = (): ApolloClient<NormalizedCacheObject> => {
  apolloClient = new ApolloClient({
    cache: createApolloCache(),
    uri: `${process.env.REACT_APP_API_HOST}/graphql`,
    link: splitLink,
  });
  return apolloClient;
};
```

**Comment by fluorjo** [comment]
> 토큰 리프레시와 관련한 부분의 책 내용에 apolloClient 를 전역변수로 지정하는 부분에서 누락이 있는 것으로 확인하였습니다,
> 
> `createApolloClient` 함수를 다음과 같이 수정하면 `errorLink`에 `apolloClient` 가 undefined로 들어가서 발생하는 `Uncaught TypeError: Cannot read properties of undefined (reading 'mutate')` 의 문제가 해결됩니다. (@fluorjo)
> 
> ```ts
> let apolloClient: ApolloClient<NormalizedCacheObject>;
> 
> ... 링크들
> 
> export const createApolloClient = (): ApolloClient<NormalizedCacheObject> => {
>   apolloClient = new ApolloClient({
>     cache: createApolloCache(),
>     uri: `${process.env.REACT_APP_API_HOST}/graphql`,
>     link: splitLink,
>   });
>   return apolloClient;
> };
> ```

아 이렇게 하니까 해결된 것 같습니다~!
감사합니다!
