### ISSUE TITLE
[오타/문장오류] 

### ISSUE THREAD

**Issue by reyoucat** [hwasurr/graphql-book-fullstack-project#7]
### 🐛 오타 또는 문장 오류가 발견된 페이지

96p, 97p

### 🍔 오타 또는 문장 오류 내용

`as - is`
type Film { ... } // 96p
type Query { ... } // 97p
`to - be`
type Film = { ... }
type Query = { ... }

혹은 인터페이스를 오타로 친것일 수 있다.
컨펌 부탁드립니다. 뒤를 읽지 않아서요.

**Comment by hwasurr** [comment]
안녕하세요. @reyoucat 님!

먼저, 오타 및 문장오류 제보 감사드립니다.
96p와 97p의 언급하신 해당 두 코드블럭은 `Film` 오브젝트와 `films` 쿼리를 GraphQL SDL로 작성한 것입니다.
아마 타입스크립트 코드블럭으로 오해하신 것이 아닐까 생각합니다.

이런 혼동이 발생하지 않도록, 코드블럭에 작성된 언어명을 명시했으면 더 좋았을 텐데 아쉽네요.ㅠㅠ

감사합니다. 행복한 하루 되세요!! 이슈는 닫도록 하겠습니다.
