### ISSUE TITLE
[프로젝트버그] 81p 서버 graphql 최신버전 (16.6.0)에서 typegraphql 버전과 호환되지 않는 문제

### ISSUE THREAD

**Issue by reyoucat** [hwasurr/graphql-book-fullstack-project#8]
### 🐛 버그가 발견된 페이지

81p 94p, 

### 🐞 버그를 설명해주세요.

81page 에서 그냥 커멘드로 의존모듈을 한번에 설치하는데요,
버전명시하지 않고 설치하는 바람에 , 향후 94page 에서 

yarn add type-graphql 이후 1.1.1 버전이 설치 됩니다.

앞서 서버쪽에 설치된 graphql 이 "^16.6.0" 으로 설치되는데, 1.1.1 과 안맞다는 오류가 납니다.

15.5.1 로 고정해야 합니다.

yarn add graphql:15.5.1

### 🍉 버그를 재현할 방법을 알려주세요

위 내용과 상동.,

### 🌏 오류가 발생한 환경의 OS는 무엇인가요?

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by hwasurr** [comment]
안녕하세요, @reyoucat 님! 버그 제보 감사드립니다!!

해당 문제는 #4 에서도 제보되었을 만큼, 문제가 지속적으로 발생하고 있는 것 같습니다. ㅜㅜ
책이라는 소재가 인쇄 이후에 변경하는 것이 쉽지가 않아서 이를 어떻게 해결해야할 지 막막했는데요.
곰곰이 생각해 보고는, 알려진 버그 목록과 그 해결방법에 대한 페이지를 구성하고 해당 링크를 README에 남겨두는게 어떨까 생각해봤습니다. 제보주신 분들의 이슈도 위키 글에 링크시키구요.

부족한 제 책을 읽어주시고 또 활발히 활동해주셔서 너무 감사드립니다 ㅠㅠ

**Comment by reyoucat** [comment]
@hwasurr 
이거같은 경우엔 HOW-TO.md 같은곳에서 저자님의 디펜던시로 싹 다 맞추는것을 권장하면 어떨까싶네요!

**Comment by hwasurr** [comment]
넵! 그와 비슷한 방식으로 처리하도록 하겠습니다. 감사합니다!

이슈는 닫도록 하겠습니다.

**Comment by hwasurr** [comment]
[버그 목록 문서](https://github.com/hwasurr/graphql-book-fullstack-project/blob/master/bug-list.md#2-type-graphql%EC%9D%98-graphql-16-%EB%B2%84%EC%A0%84-%EC%A7%80%EC%9B%90-%EA%B4%80%EB%A0%A8-%EB%AC%B8%EC%A0%9C) 에 해당 버그 내용을 작성하였습니다.
